wandb_project: param-decomp
dtype: bfloat16
batch_size: 1024
num_iterations: 200_000
warmup_iters: 600
learning_rate: 3e-4
learning_rate_decay_frac: 0.1
weight_decay: 0.1
grad_clip: 1.0
val_loss_every: 1000
val_max_steps: 20
sample_every: 1000
intermediate_checkpoints: false

model:
  model_type: LlamaSimpleMLP
  block_size: 512
  vocab_size: 50277  # gpt-neox-20b tokenizer vocab size
  n_layer: 12
  n_head: 12
  n_embd: 768
  n_intermediate: 3072  # 768 * 4
  rotary_dim: 128       # 768 // 6
  n_ctx: 512
  n_key_value_heads: 12
  flash_attention: false

train_dataset_config:
  name: danbraunai/pile-uncopyrighted-tok-shuffled
  is_tokenized: true
  hf_tokenizer_path: EleutherAI/gpt-neox-20b
  split: train
  streaming: false
  n_ctx: 513  # model n_ctx + 1 for next-token label indexing
  seed: 0
  column_name: input_ids

val_dataset_config:
  name: danbraunai/pile-uncopyrighted-tok-shuffled
  is_tokenized: true
  hf_tokenizer_path: EleutherAI/gpt-neox-20b
  split: val
  streaming: false
  n_ctx: 513  # model n_ctx + 1 for next-token label indexing
  seed: 0
  column_name: input_ids



